version: "3.8"

services:
  postgres:
    image: postgres:12
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  back:
    depends_on:
      - postgres
    build: ./back
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    stdin_open: true
    tty: true

volumes:
  db: /backup
